desc "Run the tests and prepare for Danger"
lane :test do |options|
  # Then run tests
  scan(
    project: "Example.xcodeproj",
    scheme: "Example",
    derived_data_path: "temp/derived",
    result_bundle: true,
    code_coverage: true,
    devices: ['iPhone 16'],
    skip_package_dependencies_resolution: false
  )
end