//
//  ColorPaletteExporter.swift
//  DebugSwift
//

import UIKit

enum ColorPaletteExporter {

    static func export(_ palette: ColorPaletteSnapshot, as format: ColorPaletteExportFormat) -> String {
        switch format {
        case .swift: return swift(palette)
        case .css: return css(palette)
        case .json: return json(palette)
        case .figma: return figma(palette)
        case .tailwind: return tailwind(palette)
        case .documentation: return documentation(palette)
        }
    }

    static func swiftSnippet(for color: ColorInfo) -> String {
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
        color.color.getRed(&r, green: &g, blue: &b, alpha: &a)
        let name = identifier(for: color.name ?? color.hex, style: .camelCase)
        return """
        static let \(name) = UIColor(
            red: \(format(r)),
            green: \(format(g)),
            blue: \(format(b)),
            alpha: \(format(a))
        )
        """
    }

    private static func swift(_ palette: ColorPaletteSnapshot) -> String {
        var lines: [String] = []
        lines.append("import UIKit")
        lines.append("")
        lines.append("// Generated by DebugSwift ColorPaletteExtractor")
        if let screen = palette.screenName {
            lines.append("// Screen: \(screen)")
        }
        lines.append("extension UIColor {")
        var usedNames: Set<String> = []
        for group in palette.groups {
            lines.append("")
            lines.append("    // MARK: - \(group.category.displayName) — \(group.name)")
            for color in group.colors {
                let baseName = color.name ?? group.name
                var name = identifier(for: baseName, style: .camelCase)
                var suffix = 2
                while usedNames.contains(name) {
                    name = identifier(for: "\(baseName) \(suffix)", style: .camelCase)
                    suffix += 1
                }
                usedNames.insert(name)
                lines.append(swiftMemberSnippet(name: name, color: color))
            }
        }
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    private static func swiftMemberSnippet(name: String, color: ColorInfo) -> String {
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
        color.color.getRed(&r, green: &g, blue: &b, alpha: &a)
        return """
            static let \(name) = UIColor(
                red: \(format(r)),
                green: \(format(g)),
                blue: \(format(b)),
                alpha: \(format(a))
            ) // \(color.hex), used \(color.usageCount)×
        """
    }

    private static func css(_ palette: ColorPaletteSnapshot) -> String {
        var lines: [String] = []
        lines.append("/* Generated by DebugSwift ColorPaletteExtractor */")
        lines.append(":root {")
        var usedNames: Set<String> = []
        for group in palette.groups {
            lines.append("    /* \(group.category.displayName) — \(group.name) */")
            for color in group.colors {
                let baseName = color.name ?? group.name
                var name = identifier(for: baseName, style: .kebabCase)
                var suffix = 2
                while usedNames.contains(name) {
                    name = identifier(for: "\(baseName)-\(suffix)", style: .kebabCase)
                    suffix += 1
                }
                usedNames.insert(name)
                lines.append("    --color-\(name): \(color.hex); /* used \(color.usageCount)× */")
            }
        }
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    private static func json(_ palette: ColorPaletteSnapshot) -> String {
        let payload: [String: Any] = [
            "screen": palette.screenName ?? NSNull(),
            "extractedAt": ISO8601DateFormatter().string(from: palette.extractedAt),
            "totalColors": palette.statistics.totalColors,
            "groups": palette.groups.map { group -> [String: Any] in
                [
                    "name": group.name,
                    "category": group.category.rawValue,
                    "totalUsage": group.totalUsage,
                    "colors": group.colors.map { color -> [String: Any] in
                        [
                            "hex": color.hex,
                            "rgb": ["r": color.red, "g": color.green, "b": color.blue],
                            "alpha": color.alpha,
                            "usage": color.usageCount
                        ]
                    }
                ]
            }
        ]
        return prettyJSON(payload)
    }

    private static func figma(_ palette: ColorPaletteSnapshot) -> String {
        var tokens: [String: Any] = [:]
        for group in palette.groups {
            var groupTokens: [String: Any] = [:]
            for color in group.colors {
                let key = identifier(for: color.name ?? color.hex, style: .kebabCase)
                groupTokens[key] = [
                    "$value": color.hex,
                    "$type": "color",
                    "$description": "Used \(color.usageCount) times"
                ]
            }
            tokens[group.name] = groupTokens
        }
        return prettyJSON(["color": tokens])
    }

    private static func tailwind(_ palette: ColorPaletteSnapshot) -> String {
        var lines: [String] = []
        lines.append("// Generated by DebugSwift ColorPaletteExtractor")
        lines.append("module.exports = {")
        lines.append("  theme: {")
        lines.append("    extend: {")
        lines.append("      colors: {")
        for group in palette.groups {
            let groupKey = identifier(for: group.name, style: .kebabCase)
            lines.append("        '\(groupKey)': {")
            for (index, color) in group.colors.enumerated() {
                let key = tailwindKey(forIndex: index)
                lines.append("          '\(key)': '\(color.hex)',")
            }
            lines.append("        },")
        }
        lines.append("      },")
        lines.append("    },")
        lines.append("  },")
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    /// Tailwind weights are 50, 100, 200, ..., 900. Map by usage rank so the
    /// most-used color is the default and rarer colors fan out to the edges.
    private static func tailwindKey(forIndex index: Int) -> String {
        if index == 0 { return "DEFAULT" }
        let scale = [100, 200, 300, 400, 500, 600, 700, 800, 900]
        let position = min(scale.count - 1, index - 1)
        return "\(scale[position])"
    }

    private static func documentation(_ palette: ColorPaletteSnapshot) -> String {
        var lines: [String] = []
        lines.append("# Color Palette")
        if let screen = palette.screenName {
            lines.append("**Screen:** \(screen)  ")
        }
        lines.append("**Extracted:** \(palette.extractedAt)  ")
        lines.append("**Total colors:** \(palette.statistics.totalColors)  ")
        lines.append("**Total usages:** \(palette.statistics.totalUsages)")
        lines.append("")

        for group in palette.groups {
            lines.append("## \(group.category.displayName) — \(group.name)")
            lines.append("")
            lines.append("| Swatch | Hex | RGB | Usage |")
            lines.append("| --- | --- | --- | --- |")
            for color in group.colors {
                let swatch = "![swatch](https://singlecolorimage.com/get/\(color.hex.replacingOccurrences(of: "#", with: ""))/40x20.png)"
                lines.append("| \(swatch) | `\(color.hex)` | \(color.rgbString) | \(color.usageCount) |")
            }
            lines.append("")
        }

        if !palette.statistics.issues.isEmpty {
            lines.append("## Issues")
            lines.append("")
            for issue in palette.statistics.issues {
                lines.append("- \(issue.message)")
            }
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Helpers

    private enum NameStyle { case camelCase, kebabCase }

    private static func identifier(for raw: String, style: NameStyle) -> String {
        let cleaned = raw
            .replacingOccurrences(of: "#", with: "")
            .replacingOccurrences(of: "(", with: " ")
            .replacingOccurrences(of: ")", with: " ")
            .replacingOccurrences(of: ",", with: " ")
        let tokens = cleaned
            .split { !$0.isLetter && !$0.isNumber }
            .map(String.init)
            .filter { !$0.isEmpty }
        guard !tokens.isEmpty else { return style == .camelCase ? "color" : "color" }

        switch style {
        case .camelCase:
            var result = tokens[0].lowercased()
            for token in tokens.dropFirst() {
                result += token.prefix(1).uppercased() + token.dropFirst().lowercased()
            }
            if let first = result.first, first.isNumber {
                result = "color" + result.prefix(1).uppercased() + result.dropFirst()
            }
            return result
        case .kebabCase:
            return tokens.map { $0.lowercased() }.joined(separator: "-")
        }
    }

    private static func format(_ value: CGFloat) -> String {
        String(format: "%.4f", Double(value))
    }

    private static func prettyJSON(_ object: Any) -> String {
        guard JSONSerialization.isValidJSONObject(object),
              let data = try? JSONSerialization.data(
                withJSONObject: object,
                options: [.prettyPrinted, .sortedKeys]
              ),
              let string = String(data: data, encoding: .utf8) else {
            return "{}"
        }
        return string
    }
}
