name: CI and Danger

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI Build and Tests
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install CocoaPods
        run: |
          cd Example
          pod install

      - name: Build Swift Package Manager
        run: |
          xcodebuild clean build \
            -project Example_SwiftUI/Example_SwiftUI.xcodeproj \
            -scheme Example_SwiftUI \
            -destination 'platform=iOS Simulator,name=iPhone 14 Plus'

      - name: Build CocoaPods and Run Tests
        run: |
          xcodebuild test \
            -workspace Example/Example.xcworkspace \
            -scheme Example \
            -destination 'platform=iOS Simulator,name=iPhone 14 Plus'

  danger:
    name: Danger Checks
    permissions: write-all
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Setup Danger
        run: |
          git clone https://github.com/MaatheusGois/DangerSwift && rm -rf DangerSwift/.git Readme.md
          mv DangerSwift/* .

      - name: Danger Stage
        run: |
          brew install danger/tap/danger-js
          swift build
          swift run danger-swift ci --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
