name: CI and Danger

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI Build and Tests
    permissions: write-all
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Build Swift Package Manager
        run: |
          xcodebuild clean build \
            -project Example/Example.xcodeproj \
            -scheme Example \
            -destination 'platform=iOS Simulator,name=iPhone 16' \

      - name: Install CocoaPods
        run: |
          cd Example
          pod install
      
      - name: Setup Danger
        run: |
          git clone https://github.com/DebugSwift/DangerSwift && rm -rf DangerSwift/.git Readme.md
          mv DangerSwift/* .
      
      - name: Test Stage
        run: |
          cd Example
          bundle install
          bundle exec fastlane test

      - name: Danger Stage
        run: |
          brew install danger/tap/danger-js
          swift build
          swift run danger-swift ci --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
