name: CI and Danger

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI Build, Tests & Danger
    permissions: write-all
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Run Fastlane tests
        run: |
          cd Example
          bundle install
          bundle exec fastlane test

      - name: Danger Stage
        run: |
          # install the JS runner
          brew install danger/tap/danger-js

          # clone the DangerSwift plugin into its own directory
          git clone https://github.com/DebugSwift/DangerSwift DangerSwiftPlugin
          cd DangerSwiftPlugin

          # build & run the plugin
          swift build
          swift run danger-swift ci --verbose
        env:
          GITHUB_TOKEN:        ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
