name: Swift Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  actions: read

jobs:
  test:
    name: Swift Tests
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
        
    - name: Run Swift Tests
      run: |
        xcodebuild test \
          -project Example/Example.xcodeproj \
          -scheme Example \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -enableCodeCoverage YES \
          IPHONEOS_DEPLOYMENT_TARGET=17.0
          
    - name: Run Package Tests
      run: |
        swift test --enable-code-coverage
        
    - name: Generate Coverage Report
      run: |
        xcrun llvm-cov export \
          .build/debug/DebugSwiftPackageTests.xctest/Contents/MacOS/DebugSwiftPackageTests \
          -instr-profile=.build/debug/codecov/default.profdata \
          -format=lcov > coverage.lcov
      continue-on-error: true
      
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.lcov
        flags: swifttests
        name: swift-tests
      continue-on-error: true 