name: Swift 6 Compatibility

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  swift6-check:
    name: Swift 6 Compatibility Check
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
        
    - name: Check Swift Version
      run: |
        swift --version
        xcodebuild -version
        
    - name: Build with Swift 6 Strict Concurrency
      run: |
        xcodebuild build \
          -project Example/Example.xcodeproj \
          -scheme Example \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          SWIFT_VERSION=6.0 \
          SWIFT_STRICT_CONCURRENCY=complete \
          IPHONEOS_DEPLOYMENT_TARGET=17.0 \
          OTHER_SWIFT_FLAGS="-strict-concurrency=complete -enable-actor-data-race-checks"
          
    - name: Build Swift Package with Strict Concurrency
      run: |
        swift build \
          -Xswiftc -strict-concurrency=complete \
          -Xswiftc -enable-actor-data-race-checks
          
    - name: Lint Swift Code
      run: |
        if [ -f ".swiftlint.yml" ]; then
          brew install swiftlint || true
          swiftlint --strict
        fi
      continue-on-error: true 