name: Minimal Test

on:
  workflow_dispatch:
  push:
    branches:
      - "maatheusgois-dd/add-rc-tags-on-pr-merge"

permissions:
  contents: write

jobs:
  test:
    name: Minimal Test
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Test
      run: echo "Test successful"