
# name: GitVersion

# on: [pull_request]

# permissions:
#    actions: write
#    checks: write
#    contents: write
#    deployments: write
#    issues: write
#    packages: write
#    pull-requests: write
#    repository-projects: write
#    security-events: write
#    statuses: write

# jobs:
#   git_version:
#     name: Determine current version
#     runs-on: ubuntu-latest
#     outputs:
#       semVer: ${{ steps.gitversion.outputs.semVer }}
#       majorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
    
#     steps:

#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         fetch-depth: 0

#     - name: Install GitVersion
#       uses: gittools/actions/gitversion/setup@v0
#       with:
#         versionSpec: '5.x'

#     - name: Determine Version
#       id: gitversion
#       uses: gittools/actions/gitversion/execute@v0

#     - name: Display GitVersion
#       run: |
#         NEW_TAG="${{ steps.gitversion.outputs.semVer }}"
#         echo "Semantic Version: $NEW_TAG"
#         echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
#   update_podspec:
#     name: Update podspec
#     needs: git_version
#     runs-on: ubuntu-latest
#     steps:
    
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Display version
#       run: |
#         PODSPEC_VERSION=$(grep -E "s\.version\s*=" DebugSwift.podspec | awk -F\' '{print $2}')
#         echo "PODSPEC_VERSION=$PODSPEC_VERSION" >> $GITHUB_ENV
#         echo Current version: '${{ needs.git_version.outputs.majorMinorPatch }}'
#         echo Podspec version: "$PODSPEC_VERSION"
#     - name: Update version
#       run: |
#         VERSION='${{ needs.git_version.outputs.majorMinorPatch }}'
#         if [ "$PODSPEC_VERSION" == "$VERSION" ]; then
#           echo Podspec version is updated.
#         else
#           echo Updating Podspec version...
#           PODSPEC_FILE="DebugSwift.podspec"
#           sed -i -E "s/(s\.version *= *')([^']+)(.*)/\1$VERSION\3/g" "$PODSPEC_FILE"
          
#           echo Committing and pushing...
#           git config user.name "GitHub Actions"
#           git config user.email "github-actions@users.noreply.github.com"
#           git add "$PODSPEC_FILE"
#           git commit -m 'feat: Update Podspec version'
#           git push
#         fi
